# Generated by Django 4.2.6 on 2023-10-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('family', models.CharField(max_length=250)),
                ('origin', models.CharField(max_length=250)),
            ],
        ),
    ]
